#!/bin/bash

set -o errexit
set -o nounset

function vendor() {
    local plugins_manifest="${1}"
    local vendordir="${2}"
    local deps=$(cat ${plugins_manifest})

    rm -rf "${vendordir}"
    mkdir -p "${vendordir}"

    for dep in ${deps}; do
        local cloneurl=$(printf "git@github.com:%s.git" ${dep})
        local clonedir=$(printf "%s/%s" ${vendordir} ${dep})
        printf "vendoring plugin[%s]\n" ${dep}
        printf "cloning[%s]\n" ${cloneurl}
        git clone "${cloneurl}" "${clonedir}"
    done

    echo
    echo "vendored deps with success"
}

vendor plugins vendor
